
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.DefaultListModel;
import javax.swing.JList;
import javax.swing.JOptionPane;

/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Administrator
 */
public class update_mobile_info extends javax.swing.JFrame {

    /**
     * Creates new form update_mobile_info
     */
    public update_mobile_info() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        MI = new javax.swing.JTextField();
        B = new javax.swing.JTextField();
        MN = new javax.swing.JTextField();
        PR = new javax.swing.JTextField();
        PP = new javax.swing.JTextField();
        SN = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jButton1.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton1.setText("GET MODEL IDs");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(20, 350, 211, 37);

        jLabel2.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel2.setText("MODEL ID");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(370, 60, 92, 21);

        jLabel3.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel3.setText("BRAND");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(370, 100, 70, 21);

        jLabel4.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel4.setText("MODEL NAME");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(370, 140, 124, 21);

        jLabel5.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel5.setText("PRICE");
        jPanel1.add(jLabel5);
        jLabel5.setBounds(370, 260, 53, 21);

        jLabel6.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel6.setText("POPULARITY");
        jPanel1.add(jLabel6);
        jLabel6.setBounds(370, 180, 130, 21);

        jLabel7.setFont(new java.awt.Font("Monotype Corsiva", 1, 18)); // NOI18N
        jLabel7.setText("STOCK NUMBER");
        jPanel1.add(jLabel7);
        jLabel7.setBounds(370, 220, 139, 21);
        jPanel1.add(MI);
        MI.setBounds(550, 60, 100, 20);
        jPanel1.add(B);
        B.setBounds(550, 100, 100, 20);
        jPanel1.add(MN);
        MN.setBounds(550, 140, 100, 20);
        jPanel1.add(PR);
        PR.setBounds(550, 260, 100, 20);
        jPanel1.add(PP);
        PP.setBounds(550, 180, 100, 20);
        jPanel1.add(SN);
        SN.setBounds(550, 220, 100, 20);

        jButton2.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton2.setText("UPDATE");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(310, 350, 140, 37);

        jButton3.setFont(new java.awt.Font("Monotype Corsiva", 1, 24)); // NOI18N
        jButton3.setText("BACK");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3);
        jButton3.setBounds(560, 345, 100, 40);

        jList1.setModel(new DefaultListModel());
        jList1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jList1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jList1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jList1);

        jPanel1.add(jScrollPane1);
        jScrollPane1.setBounds(40, 70, 130, 220);

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 36)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(102, 0, 0));
        jLabel1.setText("UPDATE MOBILE INFORMATION");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(60, 10, 600, 30);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/background2.jpg"))); // NOI18N
        jPanel1.add(jLabel8);
        jLabel8.setBounds(0, 0, 740, 460);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 736, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 459, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
         try
         {
           DefaultListModel model=(DefaultListModel)jList1.getModel();
           Class.forName("java.sql.Driver");
           Connection con=DriverManager.getConnection("jdbc:mysql://localhost/projectas","root","modi");
           Statement stmt=con.createStatement();
           String q1="select model_id from model";
           ResultSet rs=stmt.executeQuery(q1);
           while(rs.next())
           {
               model.addElement(rs.getString("model_id"));
           }

                   }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this, e.getMessage());
         }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jList1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jList1MouseClicked
        try
        {
           Class.forName("java.sql.Driver");
            Connection con=(Connection) DriverManager.getConnection("jdbc:mysql://localhost/projectas","root","modi");
            Statement stmt=(Statement) con.createStatement();
            String st=(String)jList1.getSelectedValue();
            String query="select * from model where model_id='"+(st)+"';";
            ResultSet rs=stmt.executeQuery(query);

           while(rs.next())
            {
                String mi=rs.getString("model_id");
                MI.setText(mi);
                String b=rs.getString("brand");B.setText(b);
                String mn=rs.getString("model_name");MN.setText(mn);
                String pr=rs.getString("price");PR.setText(pr);
                String p=rs.getString("popularity");PP.setText(p);
                String sn=rs.getString("stockno");SN.setText(sn);
            }

            rs.close();
            stmt.close();
            con.close();
        }
        catch(Exception e)
        {
            JOptionPane.showMessageDialog(this,e.getMessage());
        } 
    }//GEN-LAST:event_jList1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
 try
        {
           Class.forName("java.sql.Driver");
            Connection con=DriverManager.getConnection("jdbc:mysql://localhost/projectas","root","modi");
            Statement stmt=con.createStatement();
            String st=(String)jList1.getSelectedValue();
            String mi=MI.getText();
            String n=MN.getText();
            String b=B.getText();
            String pp=PP.getText();
            String sn=SN.getText();
            String pr=PR.getText();
            String query="update model set model_id='"+(mi)+"',model_name='"+(n)+"',brand='"+(b)+"',popularity='"+(pp)+"',stockno='"+(sn)+"',price='"+(pr)+"' where model_id='"+(st)+"';";
            int i=JOptionPane.showConfirmDialog(this,"Are you sure you want to update this record",null ,JOptionPane.YES_NO_CANCEL_OPTION);
            if(i==0)
            {
               stmt.executeUpdate(query);
               JOptionPane.showMessageDialog(this,"RECORD UPDATED");
               
            }
            if(i==1)
            {
                JOptionPane.showMessageDialog(this,"RECORD NOT UPDATED");
            }
            else
            {
                
            }
        }
         catch(Exception e)
         {
             JOptionPane.showMessageDialog(this,e.getMessage());
         }       
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        new Adminpage().show();
        this.dispose();
    }//GEN-LAST:event_jButton3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(update_mobile_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(update_mobile_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(update_mobile_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(update_mobile_info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new update_mobile_info().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField B;
    private javax.swing.JTextField MI;
    private javax.swing.JTextField MN;
    private javax.swing.JTextField PP;
    private javax.swing.JTextField PR;
    private javax.swing.JTextField SN;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
